name: ci

on: pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go mod tidy
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Go mod tidy
      - run: go get github.com/securego/gosec/v2/cmd/gosec
      - run: gosec ./...
      - run: gofmt -l .
      - run: go test -cover ./...
